name: notes_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.7.1

dev_dependencies:
  build_runner: null
  freezed: ^0.9.2

flutter:
  uses-material-design: true
